services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
  web:
    build: ./chatbot
    command: >
      sh -c "
            python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_DEBUG=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped
    volumes:
      - ./chatbot:/chatbot

volumes:
  redis_data: