services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
  web:
    build: ./chatbot
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py makemigrations &&
      python manage.py collectstatic --noinput &&

      daphne -b 0.0.0.0 -p 8000 chatbot.asgi:application"
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_DEBUG=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped
    volumes:
      - ./chatbot:/chatbot 
      - staticfiles:/static
volumes:
  redis_data:
  staticfiles: